// DO NOT EDIT — generated by scripts/generate_sdk_scope_constants.py
// Source: docs/platform/scopes.yaml + docs/platform/roles.yaml
// Regenerate via `python3 scripts/generate_sdk_scope_constants.py`.

package olympus

// OlympusScope names a scope canonical string in the platform catalog.
type OlympusScope = string

const (
	// List the caller's active sessions.
	ScopeAuthSessionReadAtUser OlympusScope = "auth.session.read@user"
	// Revoke one of the caller's own sessions.
	ScopeAuthSessionDeleteAtUser OlympusScope = "auth.session.delete@user"
	// Enroll, update, or disable the caller's MFA factors.
	ScopeAuthMfaWriteAtUser OlympusScope = "auth.mfa.write@user"
	// Read the caller's tenant metadata (name, plan, hierarchy position).
	ScopePlatformTenantReadAtTenant OlympusScope = "platform.tenant.read@tenant"
	// Update tenant-level settings (display name, locale, default brand).
	ScopePlatformTenantWriteAtTenant OlympusScope = "platform.tenant.write@tenant"
	// Grant/revoke tenant administrators, rotate tenant keys, close tenant.
	ScopePlatformTenantAdminAtTenant OlympusScope = "platform.tenant.admin@tenant"
	// Read the caller's profile (name, email, avatar, preferences).
	ScopePlatformUserProfileReadAtUser OlympusScope = "platform.user.profile.read@user"
	// Update the caller's profile.
	ScopePlatformUserProfileWriteAtUser OlympusScope = "platform.user.profile.write@user"
	// List users in the tenant.
	ScopePlatformUserReadAtTenant OlympusScope = "platform.user.read@tenant"
	// Invite or update users in the tenant.
	ScopePlatformUserWriteAtTenant OlympusScope = "platform.user.write@tenant"
	// Remove a user from the tenant (soft-delete; GDPR-safe).
	ScopePlatformUserDeleteAtTenant OlympusScope = "platform.user.delete@tenant"
	// List brands within the tenant.
	ScopePlatformBrandReadAtTenant OlympusScope = "platform.brand.read@tenant"
	// Create or update brands within the tenant.
	ScopePlatformBrandWriteAtTenant OlympusScope = "platform.brand.write@tenant"
	// List locations within the tenant.
	ScopePlatformLocationReadAtTenant OlympusScope = "platform.location.read@tenant"
	// Create or update locations.
	ScopePlatformLocationWriteAtTenant OlympusScope = "platform.location.write@tenant"
	// Pair a device to the authenticated user for PIN-only subsequent logins.
	ScopePlatformDeviceAuthorizeExecuteAtUser OlympusScope = "platform.device.authorize.execute@user"
	// Revoke a device binding for the authenticated user.
	ScopePlatformDeviceUnbindDeleteAtUser OlympusScope = "platform.device.unbind.delete@user"
	// Read orders for the tenant.
	ScopeCommerceOrderReadAtTenant OlympusScope = "commerce.order.read@tenant"
	// Create or update orders.
	ScopeCommerceOrderWriteAtTenant OlympusScope = "commerce.order.write@tenant"
	// Void or cancel orders.
	ScopeCommerceOrderDeleteAtTenant OlympusScope = "commerce.order.delete@tenant"
	// Read customer records.
	ScopeCommerceCustomerReadAtTenant OlympusScope = "commerce.customer.read@tenant"
	// Create or update customer records.
	ScopeCommerceCustomerWriteAtTenant OlympusScope = "commerce.customer.write@tenant"
	// Read inventory levels.
	ScopeCommerceInventoryReadAtTenant OlympusScope = "commerce.inventory.read@tenant"
	// Adjust inventory.
	ScopeCommerceInventoryWriteAtTenant OlympusScope = "commerce.inventory.write@tenant"
	// Read product catalog.
	ScopeCommerceCatalogReadAtTenant OlympusScope = "commerce.catalog.read@tenant"
	// Create or update products.
	ScopeCommerceCatalogWriteAtTenant OlympusScope = "commerce.catalog.write@tenant"
	// Invoke AI inference against the Ether router (chat, completion, embed).
	ScopeAiInferenceExecuteAtTenant OlympusScope = "ai.inference.execute@tenant"
	// Invoke an Ether-managed agent (Pantheon or custom).
	ScopeAiAgentExecuteAtTenant OlympusScope = "ai.agent.execute@tenant"
	// Manage tenant-level AI model configuration (custom tiers, routing overrides).
	ScopeAiModelAdminAtTenant OlympusScope = "ai.model.admin@tenant"
	// Read payment records.
	ScopePayPaymentReadAtTenant OlympusScope = "pay.payment.read@tenant"
	// Initiate payment captures.
	ScopePayPaymentWriteAtTenant OlympusScope = "pay.payment.write@tenant"
	// Issue refunds for captured payments.
	ScopePayRefundExecuteAtTenant OlympusScope = "pay.refund.execute@tenant"
	// Read payout records.
	ScopePayPayoutReadAtTenant OlympusScope = "pay.payout.read@tenant"
	// Send transactional emails through Olympus Notify.
	ScopeNotifyEmailWriteAtTenant OlympusScope = "notify.email.write@tenant"
	// Send SMS messages.
	ScopeNotifySmsWriteAtTenant OlympusScope = "notify.sms.write@tenant"
	// Send push notifications.
	ScopeNotifyPushWriteAtTenant OlympusScope = "notify.push.write@tenant"
	// Register/deregister FCM device tokens for the authenticated user.
	ScopeNotifyDevicesWriteAtUser OlympusScope = "notify.devices.write@user"
	// Subscribe the authenticated user's devices to public notification topics.
	ScopeNotifyTopicsSubscribeAtUser OlympusScope = "notify.topics.subscribe@user"
	// Subscribe arbitrary users/devices to privileged topics (e.g. role-gated topics).
	ScopeNotifyTopicsAdminAtTenant OlympusScope = "notify.topics.admin@tenant"
	// Read domain events from the tenant's event stream.
	ScopeEventsStreamReadAtTenant OlympusScope = "events.stream.read@tenant"
	// Publish domain events.
	ScopeEventsStreamWriteAtTenant OlympusScope = "events.stream.write@tenant"
	// Execute declarative queries against the tenant's data surface.
	ScopeDataQueryExecuteAtTenant OlympusScope = "data.query.execute@tenant"
	// Read pre-computed analytics cubes.
	ScopeDataCubeReadAtTenant OlympusScope = "data.cube.read@tenant"
	// Read files in tenant R2 buckets.
	ScopeStorageFileReadAtTenant OlympusScope = "storage.file.read@tenant"
	// Upload or replace files.
	ScopeStorageFileWriteAtTenant OlympusScope = "storage.file.write@tenant"
	// Delete files.
	ScopeStorageFileDeleteAtTenant OlympusScope = "storage.file.delete@tenant"
	// Read marketplace listings.
	ScopeMarketplaceListingReadAtTenant OlympusScope = "marketplace.listing.read@tenant"
	// Install or remove apps from the marketplace.
	ScopeMarketplaceInstallWriteAtTenant OlympusScope = "marketplace.install.write@tenant"
	// Read active subscriptions.
	ScopeBillingSubscriptionReadAtTenant OlympusScope = "billing.subscription.read@tenant"
	// Change subscription plan, add-ons, or quantity.
	ScopeBillingSubscriptionWriteAtTenant OlympusScope = "billing.subscription.write@tenant"
	// Read invoices.
	ScopeBillingInvoiceReadAtTenant OlympusScope = "billing.invoice.read@tenant"
	// Read feature-gating policies.
	ScopeGatingPolicyReadAtTenant OlympusScope = "gating.policy.read@tenant"
	// Write feature-gating overrides.
	ScopeGatingPolicyWriteAtTenant OlympusScope = "gating.policy.write@tenant"
	// Read registered kiosks.
	ScopeDevicesKioskReadAtTenant OlympusScope = "devices.kiosk.read@tenant"
	// Register, configure, or pair kiosks.
	ScopeDevicesKioskWriteAtTenant OlympusScope = "devices.kiosk.write@tenant"
	// Register or reconfigure printers.
	ScopeDevicesPrinterWriteAtTenant OlympusScope = "devices.printer.write@tenant"
	// Register cameras and configure vision pipelines.
	ScopeDevicesCameraAdminAtTenant OlympusScope = "devices.camera.admin@tenant"
	// Read observability logs scoped to the tenant.
	ScopeObserveLogReadAtTenant OlympusScope = "observe.log.read@tenant"
	// Read metrics.
	ScopeObserveMetricReadAtTenant OlympusScope = "observe.metric.read@tenant"
	// Create or update alert rules.
	ScopeObserveAlertWriteAtTenant OlympusScope = "observe.alert.write@tenant"
	// Read call records (metadata only, not transcripts).
	ScopeVoiceCallReadAtTenant OlympusScope = "voice.call.read@tenant"
	// Place or modify voice calls.
	ScopeVoiceCallWriteAtTenant OlympusScope = "voice.call.write@tenant"
	// Read call transcripts.
	ScopeVoiceTranscriptReadAtTenant OlympusScope = "voice.transcript.read@tenant"
	// Provision, port, or release voice numbers.
	ScopeVoiceNumberAdminAtTenant OlympusScope = "voice.number.admin@tenant"
	// Configure voice agents (pipeline, prompts, fallback).
	ScopeVoiceAgentAdminAtTenant OlympusScope = "voice.agent.admin@tenant"
	// Read agent-workflow runs.
	ScopeWorkflowsRunReadAtTenant OlympusScope = "workflows.run.read@tenant"
	// Trigger agent-workflow runs.
	ScopeWorkflowsRunExecuteAtTenant OlympusScope = "workflows.run.execute@tenant"
	// Create or update workflow definitions.
	ScopeWorkflowsDefinitionWriteAtTenant OlympusScope = "workflows.definition.write@tenant"
	// Read leads.
	ScopeConnectLeadReadAtTenant OlympusScope = "connect.lead.read@tenant"
	// Create or update leads.
	ScopeConnectLeadWriteAtTenant OlympusScope = "connect.lead.write@tenant"
	// Read opportunities / deals.
	ScopeConnectOpportunityReadAtTenant OlympusScope = "connect.opportunity.read@tenant"
	// Create or update opportunities.
	ScopeConnectOpportunityWriteAtTenant OlympusScope = "connect.opportunity.write@tenant"
	// Read external-IDP configuration.
	ScopeIdentityFederationReadAtTenant OlympusScope = "identity.federation.read@tenant"
	// Configure SSO, SCIM, or external-IDP settings.
	ScopeIdentityFederationAdminAtTenant OlympusScope = "identity.federation.admin@tenant"
	// Read camera analytics (counts, dwell time, events).
	ScopeVisionAnalyticsReadAtTenant OlympusScope = "vision.analytics.read@tenant"
	// Run recognition models against camera feeds.
	ScopeVisionRecognitionExecuteAtTenant OlympusScope = "vision.recognition.execute@tenant"
	// Read message threads in the tenant's inbox.
	ScopeMessagesThreadReadAtTenant OlympusScope = "messages.thread.read@tenant"
	// Send messages on behalf of the tenant.
	ScopeMessagesThreadWriteAtTenant OlympusScope = "messages.thread.write@tenant"
	// Read the caller's own inbox.
	ScopeMessagesInboxReadAtUser OlympusScope = "messages.inbox.read@user"
	// Forward-geocode a street address to lat/lng coordinates.
	ScopeMapsGeocodeReadAtApp OlympusScope = "maps.geocode.read@app"
	// Reverse-geocode lat/lng coordinates (often from user device) to an address.
	ScopeMapsReverseGeocodeReadAtTenant OlympusScope = "maps.reverse_geocode.read@tenant"
	// Validate whether an address or coordinate falls within configured delivery zones.
	ScopeMapsDeliveryZoneExecuteAtTenant OlympusScope = "maps.delivery_zone.execute@tenant"
	// Build a provider-specific directions URL (Waze / Google Maps / Apple Maps / OSM).
	ScopeMapsDirectionsUrlReadAtApp OlympusScope = "maps.directions_url.read@app"
	// Read POS register state.
	ScopePosRegisterReadAtTenant OlympusScope = "pos.register.read@tenant"
	// Record POS transactions.
	ScopePosTransactionWriteAtTenant OlympusScope = "pos.transaction.write@tenant"
	// Submit voice-originated orders to the POS.
	ScopePosVoiceOrderExecuteAtTenant OlympusScope = "pos.voice_order.execute@tenant"
	// Read ad campaigns.
	ScopeAdsCampaignReadAtTenant OlympusScope = "ads.campaign.read@tenant"
	// Create or update ad campaigns.
	ScopeAdsCampaignWriteAtTenant OlympusScope = "ads.campaign.write@tenant"
	// Read developer app records owned by the tenant.
	ScopeDeveloperAppReadAtTenant OlympusScope = "developer.app.read@tenant"
	// Submit, update, or publish developer apps.
	ScopeDeveloperAppAdminAtTenant OlympusScope = "developer.app.admin@tenant"
	// Read the caller's health/wellness records.
	ScopeHealthRecordReadAtUser OlympusScope = "health.record.read@user"
	// Add to the caller's health records.
	ScopeHealthRecordWriteAtUser OlympusScope = "health.record.write@user"
	// Read the PizzaOS menu (items, categories, modifiers, price history).
	ScopePizzaMenuReadAtTenant OlympusScope = "pizza.menu.read@tenant"
	// Create or update menu items.
	ScopePizzaMenuWriteAtTenant OlympusScope = "pizza.menu.write@tenant"
	// Read pizza orders.
	ScopePizzaOrdersReadAtTenant OlympusScope = "pizza.orders.read@tenant"
	// Create or update pizza orders.
	ScopePizzaOrdersWriteAtTenant OlympusScope = "pizza.orders.write@tenant"
	// Issue refunds / void completed orders (hits pay.refund + commerce.cancelOrder).
	ScopePizzaOrdersRefundAtTenant OlympusScope = "pizza.orders.refund@tenant"
	// Read pizza customer records.
	ScopePizzaCustomersReadAtTenant OlympusScope = "pizza.customers.read@tenant"
	// Create or update customer records (addresses, caller-ID matches, notes).
	ScopePizzaCustomersWriteAtTenant OlympusScope = "pizza.customers.write@tenant"
	// Read delivery zones.
	ScopePizzaDeliveryZonesReadAtTenant OlympusScope = "pizza.delivery_zones.read@tenant"
	// Update delivery zones.
	ScopePizzaDeliveryZonesWriteAtTenant OlympusScope = "pizza.delivery_zones.write@tenant"
	// Read operating hours (consumed by menu board + customer app + phone-order flow).
	ScopePizzaHoursReadAtTenant OlympusScope = "pizza.hours.read@tenant"
	// Update operating hours.
	ScopePizzaHoursWriteAtTenant OlympusScope = "pizza.hours.write@tenant"
	// Read loyalty program state (customer points, tiers, rewards).
	ScopePizzaLoyaltyReadAtTenant OlympusScope = "pizza.loyalty.read@tenant"
	// Adjust loyalty balances and rules.
	ScopePizzaLoyaltyWriteAtTenant OlympusScope = "pizza.loyalty.write@tenant"
	// Read deals / promos (BOGO, % off, $ off, combos, time-window, day-of-week).
	ScopePizzaDealsReadAtTenant OlympusScope = "pizza.deals.read@tenant"
	// Create or update deals + coupon codes.
	ScopePizzaDealsWriteAtTenant OlympusScope = "pizza.deals.write@tenant"
	// Administer deal budgets, redemption caps, corp-mandated deals (requires franchise trust).
	ScopePizzaDealsAdminAtTenant OlympusScope = "pizza.deals.admin@tenant"
	// Read driver roster + current GPS/assignment state.
	ScopePizzaDriversReadAtTenant OlympusScope = "pizza.drivers.read@tenant"
	// Dispatch drivers, update assignments, record deliveries.
	ScopePizzaDriversWriteAtTenant OlympusScope = "pizza.drivers.write@tenant"
	// Read KDS ticket queue, oven slot tracking, bump events.
	ScopePizzaKitchenReadAtTenant OlympusScope = "pizza.kitchen.read@tenant"
	// Bump tickets, update oven slots, invoke prep-forecast agent.
	ScopePizzaKitchenWriteAtTenant OlympusScope = "pizza.kitchen.write@tenant"
	// Read owner analytics — food cost, labor %, review aggregates, demand anomalies (aggregated).
	ScopePizzaReportsReadAtTenant OlympusScope = "pizza.reports.read@tenant"
	// Read operational inventory state (86 list, waste log, real-time counts).
	ScopePizzaInventoryReadAtTenant OlympusScope = "pizza.inventory.read@tenant"
	// Mark items 86, log waste, adjust real-time counts.
	ScopePizzaInventoryWriteAtTenant OlympusScope = "pizza.inventory.write@tenant"
	// Read aggregated review data (Google, Yelp, delivery platforms) + sentiment.
	ScopePizzaReviewsReadAtTenant OlympusScope = "pizza.reviews.read@tenant"
	// Draft or post review responses on behalf of the tenant.
	ScopePizzaReviewsWriteAtTenant OlympusScope = "pizza.reviews.write@tenant"
	// Corporate franchise administration over location-tenants within the same company. Cross-tenant access is authorized via policy-layer company_id check (JWT.company_id must match target tenant's company_id). No @org holder in 1.0 — company scoping lives in policy layer, not claim layer. See pizza-os#77 reply for design call.
	ScopePizzaFranchiseAdminAtTenant OlympusScope = "pizza.franchise.admin@tenant"
	// Read OrderEchoAI orders (voice + chat originated).
	ScopeOrderechoOrderReadAtTenant OlympusScope = "orderecho.order.read@tenant"
	// Submit or update orders.
	ScopeOrderechoOrderWriteAtTenant OlympusScope = "orderecho.order.write@tenant"
	// Cancel orders.
	ScopeOrderechoOrderCancelAtTenant OlympusScope = "orderecho.order.cancel@tenant"
	// Read the OrderEchoAI-managed menu projection.
	ScopeOrderechoMenuReadAtTenant OlympusScope = "orderecho.menu.read@tenant"
	// Read customer profiles.
	ScopeOrderechoCustomerReadAtTenant OlympusScope = "orderecho.customer.read@tenant"
	// Collect payment for voice orders.
	ScopeOrderechoPaymentWriteAtTenant OlympusScope = "orderecho.payment.write@tenant"
	// Read voice transcripts captured by OrderEchoAI.
	ScopeOrderechoVoiceTranscriptReadAtTenant OlympusScope = "orderecho.voice.transcript.read@tenant"
	// Read the bar menu.
	ScopeBarMenuReadAtTenant OlympusScope = "bar.menu.read@tenant"
	// Update the bar menu.
	ScopeBarMenuWriteAtTenant OlympusScope = "bar.menu.write@tenant"
	// Read open and closed tabs.
	ScopeBarTabsReadAtTenant OlympusScope = "bar.tabs.read@tenant"
	// Open, update, and close tabs.
	ScopeBarTabsWriteAtTenant OlympusScope = "bar.tabs.write@tenant"
	// Void tabs (compliance-audited).
	ScopeBarTabsVoidAtTenant OlympusScope = "bar.tabs.void@tenant"
	// Read bar inventory.
	ScopeBarInventoryReadAtTenant OlympusScope = "bar.inventory.read@tenant"
	// Adjust bar inventory.
	ScopeBarInventoryWriteAtTenant OlympusScope = "bar.inventory.write@tenant"
	// Update operating hours.
	ScopeBarHoursWriteAtTenant OlympusScope = "bar.hours.write@tenant"
	// Record age verification events for legal compliance.
	ScopeBarAgeVerificationWriteAtTenant OlympusScope = "bar.age_verification.write@tenant"
	// Read bar loyalty program state.
	ScopeBarLoyaltyReadAtTenant OlympusScope = "bar.loyalty.read@tenant"
	// Adjust loyalty balances and rules.
	ScopeBarLoyaltyWriteAtTenant OlympusScope = "bar.loyalty.write@tenant"
	// Update staff schedules.
	ScopeBarStaffScheduleWriteAtTenant OlympusScope = "bar.staff.schedule.write@tenant"
	// Submit voice-originated bar orders.
	ScopeBarVoiceOrderExecuteAtTenant OlympusScope = "bar.voice.order.execute@tenant"
	// Read the user's connected smart-home state.
	ScopeAuraSmartHomeReadAtUser OlympusScope = "aura.smart_home.read@user"
	// Control smart-home devices.
	ScopeAuraSmartHomeWriteAtUser OlympusScope = "aura.smart_home.write@user"
	// Pair or remove smart-home devices and change automation rules.
	ScopeAuraSmartHomeAdminAtUser OlympusScope = "aura.smart_home.admin@user"
	// Read the user's calendar.
	ScopeAuraCalendarReadAtUser OlympusScope = "aura.calendar.read@user"
	// Create or update calendar events.
	ScopeAuraCalendarWriteAtUser OlympusScope = "aura.calendar.write@user"
	// Read the user's messages (email, SMS snippets).
	ScopeAuraMessagesReadAtUser OlympusScope = "aura.messages.read@user"
	// Read the user's current location.
	ScopeAuraLocationReadAtUser OlympusScope = "aura.location.read@user"
	// Execute voice commands on the user's behalf (may trigger smart-home actions).
	ScopeAuraVoiceCommandExecuteAtUser OlympusScope = "aura.voice.command.execute@user"
	// Read the user's health and activity data.
	ScopeAuraHealthReadAtUser OlympusScope = "aura.health.read@user"
	// Post or schedule posts to the user's connected third-party social accounts (Twitter/X, Instagram, Facebook, etc.). Requested per maximus-ai#35 2026-04-18.
	ScopeAuraSocialPublishAtUser OlympusScope = "aura.social.publish@user"
	// Read CallStackAI call records.
	ScopeCallstackCallReadAtTenant OlympusScope = "callstack.call.read@tenant"
	// Place or manage calls via CallStackAI.
	ScopeCallstackCallWriteAtTenant OlympusScope = "callstack.call.write@tenant"
	// Configure CallStack voice agents (prompts, escalation, on-call routing).
	ScopeCallstackAgentAdminAtTenant OlympusScope = "callstack.agent.admin@tenant"
)

// OlympusScopesAll enumerates every scope canonical string.
var OlympusScopesAll = []OlympusScope{
	"auth.session.read@user",
	"auth.session.delete@user",
	"auth.mfa.write@user",
	"platform.tenant.read@tenant",
	"platform.tenant.write@tenant",
	"platform.tenant.admin@tenant",
	"platform.user.profile.read@user",
	"platform.user.profile.write@user",
	"platform.user.read@tenant",
	"platform.user.write@tenant",
	"platform.user.delete@tenant",
	"platform.brand.read@tenant",
	"platform.brand.write@tenant",
	"platform.location.read@tenant",
	"platform.location.write@tenant",
	"platform.device.authorize.execute@user",
	"platform.device.unbind.delete@user",
	"commerce.order.read@tenant",
	"commerce.order.write@tenant",
	"commerce.order.delete@tenant",
	"commerce.customer.read@tenant",
	"commerce.customer.write@tenant",
	"commerce.inventory.read@tenant",
	"commerce.inventory.write@tenant",
	"commerce.catalog.read@tenant",
	"commerce.catalog.write@tenant",
	"ai.inference.execute@tenant",
	"ai.agent.execute@tenant",
	"ai.model.admin@tenant",
	"pay.payment.read@tenant",
	"pay.payment.write@tenant",
	"pay.refund.execute@tenant",
	"pay.payout.read@tenant",
	"notify.email.write@tenant",
	"notify.sms.write@tenant",
	"notify.push.write@tenant",
	"notify.devices.write@user",
	"notify.topics.subscribe@user",
	"notify.topics.admin@tenant",
	"events.stream.read@tenant",
	"events.stream.write@tenant",
	"data.query.execute@tenant",
	"data.cube.read@tenant",
	"storage.file.read@tenant",
	"storage.file.write@tenant",
	"storage.file.delete@tenant",
	"marketplace.listing.read@tenant",
	"marketplace.install.write@tenant",
	"billing.subscription.read@tenant",
	"billing.subscription.write@tenant",
	"billing.invoice.read@tenant",
	"gating.policy.read@tenant",
	"gating.policy.write@tenant",
	"devices.kiosk.read@tenant",
	"devices.kiosk.write@tenant",
	"devices.printer.write@tenant",
	"devices.camera.admin@tenant",
	"observe.log.read@tenant",
	"observe.metric.read@tenant",
	"observe.alert.write@tenant",
	"voice.call.read@tenant",
	"voice.call.write@tenant",
	"voice.transcript.read@tenant",
	"voice.number.admin@tenant",
	"voice.agent.admin@tenant",
	"workflows.run.read@tenant",
	"workflows.run.execute@tenant",
	"workflows.definition.write@tenant",
	"connect.lead.read@tenant",
	"connect.lead.write@tenant",
	"connect.opportunity.read@tenant",
	"connect.opportunity.write@tenant",
	"identity.federation.read@tenant",
	"identity.federation.admin@tenant",
	"vision.analytics.read@tenant",
	"vision.recognition.execute@tenant",
	"messages.thread.read@tenant",
	"messages.thread.write@tenant",
	"messages.inbox.read@user",
	"maps.geocode.read@app",
	"maps.reverse_geocode.read@tenant",
	"maps.delivery_zone.execute@tenant",
	"maps.directions_url.read@app",
	"pos.register.read@tenant",
	"pos.transaction.write@tenant",
	"pos.voice_order.execute@tenant",
	"ads.campaign.read@tenant",
	"ads.campaign.write@tenant",
	"developer.app.read@tenant",
	"developer.app.admin@tenant",
	"health.record.read@user",
	"health.record.write@user",
	"pizza.menu.read@tenant",
	"pizza.menu.write@tenant",
	"pizza.orders.read@tenant",
	"pizza.orders.write@tenant",
	"pizza.orders.refund@tenant",
	"pizza.customers.read@tenant",
	"pizza.customers.write@tenant",
	"pizza.delivery_zones.read@tenant",
	"pizza.delivery_zones.write@tenant",
	"pizza.hours.read@tenant",
	"pizza.hours.write@tenant",
	"pizza.loyalty.read@tenant",
	"pizza.loyalty.write@tenant",
	"pizza.deals.read@tenant",
	"pizza.deals.write@tenant",
	"pizza.deals.admin@tenant",
	"pizza.drivers.read@tenant",
	"pizza.drivers.write@tenant",
	"pizza.kitchen.read@tenant",
	"pizza.kitchen.write@tenant",
	"pizza.reports.read@tenant",
	"pizza.inventory.read@tenant",
	"pizza.inventory.write@tenant",
	"pizza.reviews.read@tenant",
	"pizza.reviews.write@tenant",
	"pizza.franchise.admin@tenant",
	"orderecho.order.read@tenant",
	"orderecho.order.write@tenant",
	"orderecho.order.cancel@tenant",
	"orderecho.menu.read@tenant",
	"orderecho.customer.read@tenant",
	"orderecho.payment.write@tenant",
	"orderecho.voice.transcript.read@tenant",
	"bar.menu.read@tenant",
	"bar.menu.write@tenant",
	"bar.tabs.read@tenant",
	"bar.tabs.write@tenant",
	"bar.tabs.void@tenant",
	"bar.inventory.read@tenant",
	"bar.inventory.write@tenant",
	"bar.hours.write@tenant",
	"bar.age_verification.write@tenant",
	"bar.loyalty.read@tenant",
	"bar.loyalty.write@tenant",
	"bar.staff.schedule.write@tenant",
	"bar.voice.order.execute@tenant",
	"aura.smart_home.read@user",
	"aura.smart_home.write@user",
	"aura.smart_home.admin@user",
	"aura.calendar.read@user",
	"aura.calendar.write@user",
	"aura.messages.read@user",
	"aura.location.read@user",
	"aura.voice.command.execute@user",
	"aura.health.read@user",
	"aura.social.publish@user",
	"callstack.call.read@tenant",
	"callstack.call.write@tenant",
	"callstack.agent.admin@tenant",
}
