// DO NOT EDIT — generated by scripts/generate_sdk_scope_constants.py
// Source: docs/platform/scopes.yaml + docs/platform/roles.yaml
// Regenerate via `python3 scripts/generate_sdk_scope_constants.py`.

package olympus

// OlympusRole names a role canonical string.
type OlympusRole = string

const (
	// Break-glass root. Emergency-only. All platform scopes.
	RoleSuperAdmin OlympusRole = "super_admin"
	// System-level administrative access across all tenants. Used by internal SREs.
	RoleSystemAdmin OlympusRole = "system_admin"
	// Day-to-day platform operations — tenant CRUD, app install review, HITL approvals.
	RolePlatformOperator OlympusRole = "platform_operator"
	// Platform administrative role for product + developer-experience operations.
	RolePlatformAdmin OlympusRole = "platform_admin"
	// Full control of a single tenant — user management, app installs, billing, settings.
	RoleTenantAdmin OlympusRole = "tenant_admin"
	// Tenant billing/legal owner. Often same person as tenant_admin but tracked separately for compliance.
	RoleTenantOwner OlympusRole = "tenant_owner"
	// Operational manager within a tenant — staff management, reporting, non-billing settings.
	RoleManager OlympusRole = "manager"
	// Shift supervisor — can approve overrides, adjust orders, view team reports.
	RoleSupervisor OlympusRole = "supervisor"
	// Line-level staff — POS, kitchen, counter. Read-only on reports by default.
	RoleStaff OlympusRole = "staff"
	// Baseline tenant-attached identity with no operational role. Customers, guests, invited users before role assignment.
	RoleUser OlympusRole = "user"
	// Restaurant GM/FOH-manager — menu, staff, reservations, POS overrides.
	RoleRestaurantManager OlympusRole = "restaurant_manager"
	// Bar-vertical staff — dram-shop compliance, age verification workflows.
	RoleBartender OlympusRole = "bartender"
	// Delivery driver — route/order assignment, geofence pickup.
	RoleDriver OlympusRole = "driver"
	// Admin of an installed app's own configuration (app-level settings, not tenant settings).
	RoleAppAdmin OlympusRole = "app_admin"
	// Baseline user interacting with an installed app without admin powers.
	RoleAppUser OlympusRole = "app_user"
	// Device principal (POS terminal, kiosk, KDS). Subject format `device:<uuid>`. Calls are bounded to registered device surface.
	RoleDevice OlympusRole = "device"
)

var OlympusRolesAll = []OlympusRole{
	"super_admin",
	"system_admin",
	"platform_operator",
	"platform_admin",
	"tenant_admin",
	"tenant_owner",
	"manager",
	"supervisor",
	"staff",
	"user",
	"restaurant_manager",
	"bartender",
	"driver",
	"app_admin",
	"app_user",
	"device",
}

// Roles that grant global platform control. Matches `backend/rust/platform/src/middleware/rbac.rs:PLATFORM_ADMIN_ROLES`.
var PlatformAdminRoles = []OlympusRole{
	"platform_admin",
	"platform_operator",
	"system_admin",
	"super_admin",
}

// Roles that can manage tenant-scoped resources. Matches `TENANT_ADMIN_ROLES` in Rust middleware.
var TenantAdminRoles = []OlympusRole{
	"tenant_admin",
	"tenant_owner",
	"platform_admin",
	"platform_operator",
	"system_admin",
	"super_admin",
}

// Roles that can operate tenant resources (managers, supervisors, admins). Matches `TENANT_OPERATOR_ROLES` in Rust middleware.
var TenantOperatorRoles = []OlympusRole{
	"manager",
	"supervisor",
	"restaurant_manager",
	"tenant_admin",
	"tenant_owner",
	"platform_admin",
	"platform_operator",
	"system_admin",
	"super_admin",
}
